version: "3.8"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - PORT=3000
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=cicd_practice_prod
            - DB_USER=postgres
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
        deploy:
            replicas: 3
            update_config:
                parallelism: 1
                delay: 10s

    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=cicd_practice_prod
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres_prod_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    postgres_prod_data:
