version: "3.8"

services:
    app:
        build: .
        ports:
            - "3001:3000"
        environment:
            - NODE_ENV=staging
            - PORT=3000
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=cicd_practice_staging
            - DB_USER=postgres
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
        deploy:
            replicas: 2

    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=cicd_practice_staging
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres_staging_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    postgres_staging_data:
